# Generated by Django 5.0.4 on 2024-05-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ais_e_bike_app', '0002_alter_register_form_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='cntact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emai_id', models.EmailField(max_length=30)),
                ('messages', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Provider_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('Username', models.FileField(max_length=30, upload_to='')),
                ('phone_number', models.BigIntegerField()),
                ('password', models.CharField(max_length=18)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('vekele_number', models.CharField(max_length=20)),
                ('RC', models.FileField(upload_to='')),
            ],
        ),
    ]
