# Generated by Django 5.0.4 on 2024-05-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ais_e_bike_app', '0004_provider_register_passwordr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addvaickal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vai_name', models.CharField(max_length=50)),
                ('RC', models.FileField(upload_to='')),
                ('cost', models.IntegerField()),
                ('duretion', models.IntegerField()),
                ('cost_per_hr', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='vaik_taking_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Phone_valid', models.BigIntegerField()),
                ('licence', models.FileField(upload_to='')),
                ('taker_img', models.ImageField(upload_to='')),
                ('time_to_take_days', models.IntegerField()),
                ('time_in_hr', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='provider_register',
            name='RC',
        ),
        migrations.AddField(
            model_name='provider_register',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
