# Generated by Django 5.0.4 on 2024-05-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ais_e_bike_app', '0005_addvaickal_vaik_taking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvaickal',
            name='duretion',
        ),
        migrations.AddField(
            model_name='addvaickal',
            name='vai_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
